__init__.py data.json data_format.json devices.json test.sh testing_project.json testing_project.sh testing_result uploads uploads_project_json daemon not running. starting it now at tcp:5037 __init__.py data.json data_format.json devices.json test.sh testing_project.json testing_project.sh testing_result uploads uploads_project_json __init__.py data.json data_format.json devices.json test.sh testing_project.json testing_project.sh testing_result uploads uploads_project_json daemon started successfully __init__.py data.json data_format.json devices.json test.sh testing_project.json testing_project.sh testing_result uploads uploads_project_json adb: error: failed to get feature set: device 'LGH86010d0a294' not found
